version: '3.1'

services:
    sagemath:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      ports:
          - 8888:8888
      volumes:
          - ./app:/home/sage/app